[tool.mypy]

python_version = "3.11"
disallow_untyped_defs = true
disallow_untyped_calls = true
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
exclude = ["scripts", "docs", "test"]

[[tool.mypy.overrides]]
module = "jsonpath_rw_ext"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "dnslib"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "python_hosts.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "jsonpath_rw_ext"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "jsonpath_rw_ext"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "inotify"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "inotify.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "aiosocketpool"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "isc_dhcp_leases"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "re2"
ignore_missing_imports = true

[tool.black]
line-length = 100
target-version = ['py311']